# 4월 26일 (화) - rethrows,  쥬스 메이커 프로젝트 Step1 (2)

## 🐣 학습내용

> 오늘은 쥬스 메이커 프로젝트 Step1 기능을 모두 구현해보고 PR 과정까지 진행하였다. 쥬스 메이커 프로젝트 중 FruitStore는 Class로, 그리고 JuiceMaker는 Struct로 구현되어 있었다. 어제 처음 이를 접했을 때는 깊은 고민으로 이어지지는 않았지만, 오늘은 이를 좀 더 고민해보였고, 다음의 이유 때문에 이렇게 타입을 설정했다고 생각한다. 아래의 예시는 [https://jeonyeohun.tistory.com/179](https://jeonyeohun.tistory.com/179)를 보고 만들어 보았다.
> 

- Class 내부 Struct 구조

```swift
struct StructType {
    var number = 1
}

class ClassType {
    var number = 2
    var someStruct = StructType()
}

let someClass = ClassType()
let someClassCopy = someClass

someClassCopy.number = 222
someClassCopy.someStruct.number = 111

print(someClassCopy.number) // 222
print(someClassCopy.someStruct.number) //111

print(someClass.number) // 222
print(someClass.someStruct.number) // 111
```

> 위의 코드 결과를 보면 Class 인스턴스 생성시, Class 내부 Struct는 복사되지 않고 기존의 Struct가 사용되고 있다. 이는 Class가 참조 타입이기 때문에 참조 값을 전달하는 과정에서 내부의 값 타입인 Struct는 복사되지 않고 기존 인스턴스를 따라가기 때문이다.
> 

- Struct 내부 Class 구조

```swift
struct StructType {
    var number = 1
    var someClass = ClassType()
}

class ClassType {
    var number = 2
}

var someStruct = StructType()
var someStructCopy = someStruct

someStructCopy.number = 222
someStructCopy.someClass.number = 111

print(someStructCopy.number) // 222
print(someStructCopy.someClass.number) //111

print(someStruct.number) // 1
print(someStruct.someClass.number) // 111
```

> 위의 코드 결과를 보면 Struct 인스턴스 생성시, Struct 내부 Class 인스턴스는  참조 타입으로 참조 값이 복사되어 값에 변화가 있으면 업데이트가 이루어진다. 하지만 전체적인 구조는 Struct가 사용되고 있어 인스턴스 생성시 복사되어 사용된다. 따라서 someStructCopy는 업데이트 된 값을 사용하지만, 기존의 someSturct는 기존의 값을 사용한다.
> 

> 이를 통해, Struct 내 Class를 생성한 이유는 Class 내부에서 재고의 변화는 모두에게 똑같이 적용된다. 즉,  쥬스메이커가 몇 대가 있든 재고의 양은 모두 공유하고 있다는 것이다. 쥬스메이커는 서로 독립적이라고 보면 이해하기 편하다. 쥬스 메이커가 여러 대이면 어느 쥬스메이커는 3개의 쥬스를 만들고, 다른 쥬스메이커는 5대의 쥬스를 재고만 떨어지지 않는한 서로 관여없이 만든다는 의미이다.
> 

## 🐥 문제점 / 고민한 점

<aside>
💡 **실험 1 : class 내부 do-try-catch 문으로 인한 기능 포화**

</aside>

> 쥬스 메이커 프로젝트 Step1 도중 Struct 내부에서 makeJuice 함수를 생성하고 그 안에 입력받은 juice 값을 Switch-case문을 통해 분류하여 reduceStock()함수를 try 해보고, 오류 발생시 catch 하여 switch-case문을 통해 각 에러에 알맞는 내용을 출력하는 기능을 다루었다. 이렇게 글로 적었는데 하나의 함수 안에 너무 많은 기능들이 구현되어 있어 이를 분리할 필요성을 통감하였다.
> 

- 코드

```swift
struct JuiceMaker {
    private var JuiceMakersStore = FruitStore()
    
    func makeJuice(juice: String) {
        do {
            switch juice {
            case Juice.strawberryJuice.name:
                try JuiceMakersStore.reduceStock(fruit: Fruit.strawberry.name, amount: FruitConsumption.strawberryInStrawberryJuice)
            case Juice.bananaJuice.name:
                try JuiceMakersStore.reduceStock(fruit: Fruit.banana.name, amount: FruitConsumption.bananaInBananaJuice)
            case Juice.kiwiJuice.name:
                try JuiceMakersStore.reduceStock(fruit: Fruit.kiwi.name, amount: FruitConsumption.kiwiInKiwiJuice)
            case Juice.pineappleJuice.name:
                try JuiceMakersStore.reduceStock(fruit: Fruit.pineapple.name, amount: FruitConsumption.pineappleInPineappleJuice)
            case Juice.strawberryBananaJuice.name:
                try JuiceMakersStore.reduceStock(fruit: Fruit.strawberry.name, amount: FruitConsumption.strawberryInStrawberryBananaJuice)
                try JuiceMakersStore.reduceStock(fruit: Fruit.banana.name, amount: FruitConsumption.bananaInStrawberryBananaJuice)
            case Juice.mangoJuice.name:
                try JuiceMakersStore.reduceStock(fruit: Fruit.mango.name, amount: FruitConsumption.mangoInMangoJuice)
            case Juice.mangoKiwiJuice.name:
                try JuiceMakersStore.reduceStock(fruit: Fruit.mango.name, amount: FruitConsumption.mangoInMangoKiwiJuice)
                try JuiceMakersStore.reduceStock(fruit: Fruit.kiwi.name, amount: FruitConsumption.kiwiInMangoKiwiJuice)
            default:
                print("만들 수 없는 주스입니다")
            }
        } catch (let error) {
            switch error { //error를 매개변수로 줄 수 있다 -> 그걸 함수로 넘겨서 다른 쪽에서 처리
            case StockError.outOfStock:
                print(StockError.outOfStock.message)
            case StockError.invalidSelection:
                print(StockError.invalidSelection.message)
            default:
                print("알 수 없는 에러") //함수로 에러 처리 가능?
            }
        }
    }
}
```

## 🐓 해결방법

<aside>
💡 **실험 1 : class 내부 do-try-catch 문으로 인한 기능 포화 - Rethrows 사용**

</aside>

> 이미 throw 처리한 함수를 다시 throw 할 수 있다면 함수를 외부에 구현하여 기존의 코드를 더욱 간결하게 만들 수 있을 것임을 확신했다. 이에 Rethrows 키워드를 공부한 결과, 기존의 makeJuice() 함수를 7줄로 줄여 가독성을 높일 수 있었다. checkStock()함수를 새로 생성하여, reduceStock을 실행하기 위하여 ‘(String, Int) throws -> Void’ 파라미터 타입으로 받고, rethrows 키워드를 사용하였다. 이를 통해 내부에 try 함수를 사용하여도 오류가 발생하지 않고 내부의 기능을 수행할 수 있었다.  다음으로 catch 내 error 또한 매개변수로 처리하여 외부에 switch-case문을 내포한 handle() 함수를 생성한 뒤 에러 처리 구조를 구현하고, 이를 호출하는 형태로 수정하니, 아래의 코드로 작성할 수 있게 되었다.
> 

- 코드

```swift
struct JuiceMaker {
    var JuiceMakersStore = FruitStore()
    
    func makeJuice(of juice: String) {
        do {
            try checkStock(function: JuiceMakersStore.reduceStock(fruit:amount:), juice: juice)
        } catch (let error) {
            handle(error)
        }
    }
    
    private func checkStock(function: (String, Int) throws -> Void, juice: String) rethrows {
        switch juice {
        case Juice.strawberryJuice.name:
            try function(Fruit.strawberry.name, FruitConsumption.strawberryInStrawberryJuice)
        case Juice.bananaJuice.name:
            try function(Fruit.banana.name, FruitConsumption.bananaInBananaJuice)
        case Juice.kiwiJuice.name:
            try function(Fruit.kiwi.name, FruitConsumption.kiwiInKiwiJuice)
        case Juice.pineappleJuice.name:
            try function(Fruit.pineapple.name, FruitConsumption.pineappleInPineappleJuice)
        case Juice.strawberryBananaJuice.name:
            try function(Fruit.strawberry.name, FruitConsumption.strawberryInStrawberryBananaJuice)
            try function(Fruit.banana.name, FruitConsumption.bananaInStrawberryBananaJuice)
        case Juice.mangoJuice.name:
            try function(Fruit.mango.name, FruitConsumption.mangoInMangoJuice)
        case Juice.mangoKiwiJuice.name:
            try function(Fruit.mango.name, FruitConsumption.mangoInMangoKiwiJuice)
            try function(Fruit.kiwi.name, FruitConsumption.kiwiInMangoKiwiJuice)
        default:
            print("만들 수 없는 주스입니다")
        }
    }
    
    private func handle(_ error: Error) {
        switch error {
        case StockError.outOfStock:
            print(StockError.outOfStock.message)
        case StockError.missingProduct:
            print(StockError.missingProduct.message)
        default:
            print("알 수 없는 오류입니다")
        }
    }
}
```

## 🌐 참조

1. Struct vs Class - 전여훈 tistory

[[Swift] Struct vs. Class (2), Struct안에 참조 타입, Class 안에 값 타입 변수가 있을 때](https://jeonyeohun.tistory.com/179)

1. Rethrows - 이광연 tistory

[[Swift] rethrows란](https://gwangyonglee.tistory.com/53)